
spring:
  application:
    name: ${SPRING_APP_NAME}

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
  chat-id: ${CHAT_ID}

auth:
  receiver:
    host: ${RECEIVER_HOST}

user:
  email: ${USER_EMAIL}
  password: ${USER_PASSWORD}
  questions: ${USER_QUESTIONS}

google:
  drive:
    app:
      name: ${DRIVE_APP_NAME}

credentials:
  path: ${CREDENTIALS_PATH}
server:
  port: 8080