
spring:
  application:
    name: ${SPRING_APP_NAME}

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
  chat-id: ${CHAT_ID}

auth:
  service:
    account:
      key: ${SERVICE_ACCOUNT_KEY}

user:
  password: ${USER_PASSWORD}
  questions: ${USER_QUESTIONS}

google:
  drive:
    app:
      name: ${DRIVE_APP_NAME}

server:
  port: 8080

logging:
  level:
    sia:
      emotion_diary_bot: DEBUG
